---
title: "Planning annotations of Fiordland 2025 BRUVs"
author: "Adam Smith"
format: 
  html:
    self-contained: true
    toc: true
---

## Setup

```{r}
#| output: false
library(googlesheets4)
library(sf)
library(sfheaders)
library(tidyverse)
library(southernMaps)
library(mapview)
library(terra)
library(tidyterra)
library(rcartocolor)
library(ggnewscale)
library(ggspatial)
library(ggrepel)
library(patchwork)
theme_set(theme_bw())
```


```{r}
mark <- png::readPNG("img/mark_blank.png") |> grid::rasterGrob(interpolate=TRUE)
```

## Load NZ coastline data

... and convert to `sf` object.

```{r}
nztm <- detailed_nz_islands |> st_as_sf()
```

## Marine reserves data

```{r}
load(file = "data/mr_fiordland.Rdata")
```

## BRUV data

### Load from Google Sheet

... and convert to `sf` object.

```{r}
#| output: false
fld25 <- read_sheet(
  "https://docs.google.com/spreadsheets/d/1IQfLTiWTQnTGynuF7fUu8htJxKZuIVJw4OK6y9qRfU8",
  sheet="FLD25") |> 
  mutate(Depth = coalesce(`Depth sensor`,`Depth sounder`)) |> 
  st_as_sf(coords = c('Longitude','Latitude'), crs=4326)
```

```{r}
mapview(fld25)
```

```{r}
map_fiordland25 <- fld25 |> 
  mutate(Depth = -Depth) |> 
  mapview(zcol="Depth", layer.name = "BRUV drops (Depth)") +
  mapview(mr_fiordland |> 
            filter(Name %in% c(
              "Moana Uta (Wet Jacket Arm) Marine Reserve",
              "Taumoana (Five Finger Peninsula) Marine Reserve"
              )), 
          layer.name = "Marine Reserves", 
          col.region = "yellow")

map_fiordland25
```

```{r}
saveRDS( map_fiordland25, "maps/map_fiordland25.rds")
mapshot(map_fiordland25, url = "maps/map_fiordland25.html")
```



### Quality

```{r}
nrow(fld25)

fld25 |> 
  group_by(Quality) |> 
  summarise(n = n())
```

```{r}
fld25 |> 
  group_by(`Repeat site`) |> 
  summarise(n = n())
```

```{r}
fld25 |> summarise(
  min = min(Depth),
  max = max(Depth),
  mean = mean(Depth),
  median = median(Depth)
  )
```

```{r}
fld25 |> ggplot() + aes(x=Depth) + geom_histogram()
```

## Depths

```{r}
fld25 |> 
  ggplot() +
  aes(x = `Depth sounder`, y = `Depth sensor`) +
  geom_point() +
  geom_abline(slope=1, intercept = 0)
```

## Mappy map map

```{r}
bathy_duskbreak <- readRDS("data/bathy_duskbreak.rds")
```

```{r}
lim_tamatea_nzmg <- ext( c(2000000, 2042000, 5464000, 5488000) )
lim_duskbreak <- ext(c(xmin= 1995923, xmax = 2042666, ymin = 5464579, ymax = 5507907))
    
```

```{r}
ggmap_fld25 <- ggplot() +
  
  geom_spatraster(data = bathy_duskbreak) +
  
  geom_sf(
    data = mr_fiordland, 
    fill = "yellow", col = NA, alpha = .3
    ) +
  
  geom_sf(data = nztm, fill='grey40', colour=NA) +
  
  geom_sf(
    data = fld25,
    size = 2,
    alpha = .6
  ) +
  
  scale_fill_hypso_c(name = "Depth (m)", palette="colombia_bathy") +
  
  new_scale_fill() +
  
  scale_x_continuous(limits = lim_duskbreak[1:2], 
                     expand = c(0, 0)) +
  scale_y_continuous(limits = lim_duskbreak[3:4], 
                     expand = c(0, 0)) +
  
  annotation_scale(location = "br") +
  
  annotate("text", label = "Sea Through Science Ltd.")

ggmap_fld25
```

```{r}
mark <- png::readPNG("img/mark_blank.png") |> grid::rasterGrob(interpolate=TRUE)
```

```{r}
#| fig-height: 6
#| fig-width: 7

ggmap_fld25 + 
  annotation_custom(mark, xmin = 2028000, xmax = 2042000, ymin = 5464000, ymax = 5472000)

# ggsave("maps/ggmap_fld25.png", width = 10, height = 6, dpi = 300)
```

```{r}
ggsave(filename="maps/fld25_map.png", height = 6, width=7)
ggsave(filename="maps/fld25_map.pdf", height = 6, width=7)
```

### Maps of sites to annotate

#### Larger

```{r}
#| fig-height: 6
#| fig-width: 5

ggmap_fld25_toannotate <- ggplot() +
  
  geom_spatraster(data = bathy_duskbreak) +
  
  geom_sf(
    data = mr_fiordland, 
    fill = "yellow", col = NA, alpha = .3
    ) +
  
  geom_sf(data = nztm, fill='grey40', colour=NA) +
  
  geom_sf(
    data = fld25 |> 
      mutate(Annotated = replace_na(ToAnnotate, "No")),
    mapping = aes(colour = Annotated),
    size = 2
  ) +
  
  scale_fill_hypso_c(name = "Depth (m)", palette="colombia_bathy") +
  
  new_scale_fill() +
  
  scale_color_manual(values = c("cornsilk2", "darkorange1")) +
  
  scale_x_continuous(limits = c(lim_tamatea_nzmg[1],2018000), 
                     expand = c(0, 0)) +
  scale_y_continuous(limits = lim_tamatea_nzmg[3:4], 
                     expand = c(0, 0)) +
  
  annotation_scale(location = "br") +
  
  annotation_custom(
    mark, 
    xmin = 2011000, 
    xmax = 2018500, 
    ymin = 5463600, 
    ymax = 5469600
    ) +
  
  xlab("") + ylab("")

ggmap_fld25_toannotate
```

```{r}
ggsave(filename="maps/fld25_toannotate.png", height = 6, width=5)
ggsave(filename="maps/fld25_toannotate.pdf", height = 6, width=5)
```

#### Smaller

```{r}
#| fig-height: 5
#| fig-width: 6

ggmap_fld25_toannotate2 <- ggplot() +
  
  geom_spatraster(data = bathy_duskbreak) +
  
  geom_sf(
    data = mr_fiordland, 
    fill = "yellow", col = NA, alpha = .3
    ) +
  
  geom_sf(data = nztm, fill='grey40', colour=NA) +
  
  geom_sf(
    data = fld25 |> filter(ToAnnotate == "Yes"),
    colour = "darkorange1",
    size = 2
  ) +
  
  scale_fill_hypso_c(name = "Depth (m)", palette="colombia_bathy") +
  
  new_scale_fill() +
  
  scale_x_continuous(limits = c(2001000,2012000), 
                     expand = c(0, 0)) +
  scale_y_continuous(limits = c(5474000, lim_tamatea_nzmg[4]-4000), 
                     expand = c(0, 0)) +
  
  annotation_scale(location = "tr") +
  
  annotation_custom(
    mark, 
    xmin = 2011000, 
    xmax = 2018500, 
    ymin = 5463600, 
    ymax = 5469600
    ) +
  
  geom_label_repel(
    data = fld25 |> filter(ToAnnotate == "Yes"),
    aes(label = SiteID, geometry = geometry), 
    stat = "sf_coordinates",
    size = 2.2,
    max.overlaps = 12,
    alpha = 0.7,
    box.padding = 0.01, 
    point.padding = 0.05,
    min.segment.length = 5) +
  
  xlab("") + ylab("") + 
  
  theme(legend.position = "none")

ggmap_fld25_toannotate2
```

```{r}
ggsave(filename="maps/fld25_toannotate2.png", height = 5, width=6)
ggsave(filename="maps/fld25_toannotate2.pdf", height = 5, width=6)
```


```{r}
#| fig-width: 6
#| fig-height: 10

(ggmap_fld25_toannotate) /
  ggmap_fld25_toannotate2 +
  plot_layout(guides = "collect")

```


```{r}
ggsave(filename="maps/fld25_toannotate_both.png", height = 10, width=6)
ggsave(filename="maps/fld25_toannotate_both.pdf", height = 10, width=6)
```